# Generated by sanity_lint_review.py
# Source: review DB CSV

waive_violation -add {DeadCode-ML_739}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_740}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_741}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_742}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_743}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_744}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_745}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_746}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_747}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_748}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_749}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_750}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_763}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_764}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_765}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_766}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_751}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_752}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_753}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_754}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_755}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_756}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_757}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_758}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_759}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_760}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_761}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_762}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_767}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_768}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_769}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {DeadCode-ML_770}  -comment {Dead Code LINT warning}   -app { lint } -tag { DeadCode-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {MissingFsmStateTransition_733}  -comment {This FSM is flexible because FSM depends on the bus data width}   -app { lint } -tag { MissingFsmStateTransition } -user { pnson } -timestamp { N/A }
waive_violation -add {MissingFsmStateTransition_734}  -comment {This FSM is flexible because FSM depends on the bus data width}   -app { lint } -tag { MissingFsmStateTransition } -user { pnson } -timestamp { N/A }
waive_violation -add {MissingFsmStateTransition_732}  -comment {This FSM is flexible because FSM depends on the bus data width}   -app { lint } -tag { MissingFsmStateTransition } -user { pnson } -timestamp { N/A }
waive_violation -add {NotReachableFsmState_735}  -comment {AESDMA FSM warning is because of the flexibity for Bus width generalization. Other FSM warning is from generated ARM Async bridge.}   -app { lint } -tag { NotReachableFsmState } -user { pnson } -timestamp { N/A }
waive_violation -add {NotReachableFsmState_736}  -comment {AESDMA FSM warning is because of the flexibity for Bus width generalization. Other FSM warning is from generated ARM Async bridge.}   -app { lint } -tag { NotReachableFsmState } -user { pnson } -timestamp { N/A }
waive_violation -add {NotReachableFsmState_737}  -comment {AESDMA FSM warning is because of the flexibity for Bus width generalization. Other FSM warning is from generated ARM Async bridge.}   -app { lint } -tag { NotReachableFsmState } -user { pnson } -timestamp { N/A }
waive_violation -add {NotReachableFsmState_738}  -comment {AESDMA FSM warning is because of the flexibity for Bus width generalization. Other FSM warning is from generated ARM Async bridge.}   -app { lint } -tag { NotReachableFsmState } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_787}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_788}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_830}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_831}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_832}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_833}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {SignedUnsignedExpr-ML_771}  -comment {This is confirmed by designer}   -app { lint } -tag { SignedUnsignedExpr-ML } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_808}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_809}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_814}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_810}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_813}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_811}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_812}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_781}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_815}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_789}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_790}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_791}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_792}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_793}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_794}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_783}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_784}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_785}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_786}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_798}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_802}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_799}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_800}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_801}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_803}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_772}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_773}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_774}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_775}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_776}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_777}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_778}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_779}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_780}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_806}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_807}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_816}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_817}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_818}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_819}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_820}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_821}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_822}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_823}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_824}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_826}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_827}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_828}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_829}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_825}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_839}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_840}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_841}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_835}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_836}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W164a_837}  -comment {These counters updating logic are confirmed by designer}   -app { lint } -tag { W164a } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_1000}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_911}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_912}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_907}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_905}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_908}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_906}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_910}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_909}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_903}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_940}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_915}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_914}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_902}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_863}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_943}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_858}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_859}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W240_1011}  -comment {output port is not connected warning}   -app { lint } -tag { W240 } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1001}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1002}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1003}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1004}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1005}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1006}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1007}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1008}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1009}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1010}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_938}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_939}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_941}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_942}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_917}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_918}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_919}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_922}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_923}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_864}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_865}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_866}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_867}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_868}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_869}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_870}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_925}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_926}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_927}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_928}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_929}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_930}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_931}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_932}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_933}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_944}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_945}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_842}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_843}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_844}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_845}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_860}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_861}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1012}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1027}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1028}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1029}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1030}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1023}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1018}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1019}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1020}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1021}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W287b_1014}  -comment {output port is not connected warning}   -app { lint } -tag { W287b } -user { pnson } -timestamp { N/A }
waive_violation -add {W362_782}  -comment {In for loop state, assign could be override.These cases are confirmed by designer.}   -app { lint } -tag { W362 } -user { pnson } -timestamp { N/A }
waive_violation -add {W362_795}  -comment {In for loop state, assign could be override.These cases are confirmed by designer.}   -app { lint } -tag { W362 } -user { pnson } -timestamp { N/A }
waive_violation -add {W362_804}  -comment {In for loop state, assign could be override.These cases are confirmed by designer.}   -app { lint } -tag { W362 } -user { pnson } -timestamp { N/A }
waive_violation -add {W415a_796}  -comment {These are from combinationl logic with for loop state, which is overriding assign.}   -app { lint } -tag { W415a } -user { pnson } -timestamp { N/A }
waive_violation -add {W415a_797}  -comment {These are from combinationl logic with for loop state, which is overriding assign.}   -app { lint } -tag { W415a } -user { pnson } -timestamp { N/A }
waive_violation -add {W415a_805}  -comment {These are from combinationl logic with for loop state, which is overriding assign.}   -app { lint } -tag { W415a } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_916}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_913}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_937}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_904}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_921}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_920}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_924}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_936}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_935}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_871}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_881}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_873}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_899}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_898}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_885}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_897}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_896}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_895}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_901}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_900}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_890}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_891}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_883}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_882}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_894}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_872}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_884}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_888}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_886}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_875}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_874}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_887}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_877}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_876}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_880}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_878}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_879}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_889}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_893}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_892}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_862}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_934}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_946}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_949}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_948}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_952}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_955}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_958}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_961}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_964}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_967}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_970}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_973}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_976}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_979}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_982}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_985}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_988}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_991}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_994}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_951}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_954}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_957}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_960}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_963}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_966}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_969}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_972}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_975}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_978}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_981}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_984}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_987}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_990}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_993}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_953}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_956}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_959}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_962}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_965}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_968}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_971}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_974}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_977}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_980}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_983}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_986}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_989}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_992}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_995}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_996}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_950}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_947}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_854}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_851}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_852}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_853}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_848}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_849}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_850}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_856}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_846}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_847}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_855}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_857}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_998}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_999}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_997}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1024}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1025}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1026}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1022}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1015}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1016}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1017}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W528_1013}  -comment {output port is not connected warning}   -app { lint } -tag { W528 } -user { pnson } -timestamp { N/A }
waive_violation -add {W551_843}  -comment {This can be waived. Confirmed by the owner of SRAM safety wrapper generator.}  -filter {(Goal == "BOS_LINT_RULE") AND (Module == "ln04lpa_a00_mc_rd2rs_hsr_lvt_320x72m2b1c1_wrapper_safety_data_decoder_st_ctrl") AND (FileName == "/storage/project/atlas/design/user/pnson/ATLAS_WORKING/DK/mem/SAFETY_WRAPPER/ln04lpa_a00_mc_rd2rs_hsr_lvt_320x72m2b1c1_wrapper_safety_sf64eadi1/ln04lpa_a00_mc_rd2rs_hsr_lvt_320x72m2b1c1_wrapper_safety_sf64eadi1.sv") AND (LineNumber == "600") AND (Statement == "unique casez (r_st)")}  -app { lint } -tag { W551 } -user { pnson } -timestamp { N/A }
waive_violation -add {W551_837}  -comment {This can be waived. Confirmed by the owner of SRAM safety wrapper generator.}  -filter {(Goal == "BOS_LINT_RULE") AND (Module == "ln04lpa_a00_mc_rd2rs_hsr_lvt_32x138m2b1c1_wrapper_safety_data_decoder_st_ctrl") AND (FileName == "/storage/project/atlas/design/user/pnson/ATLAS_WORKING/DK/mem/SAFETY_WRAPPER/ln04lpa_a00_mc_rd2rs_hsr_lvt_32x138m2b1c1_wrapper_safety_sf129eadi1/ln04lpa_a00_mc_rd2rs_hsr_lvt_32x138m2b1c1_wrapper_safety_sf129eadi1.sv") AND (LineNumber == "723") AND (Statement == "unique casez (r_st)")}  -app { lint } -tag { W551 } -user { pnson } -timestamp { N/A }
